**some fundamentls for tensorflow **
*--In this notebook we cover some of the most fundamental TensorFlow *


* Introduction to tensors (creating tensors)
* Getting information from tensors (tensor attributes)
* Manipulating tensors (tensor operations)
* Tensors and NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow
* Exercises to try








In [ ]:
# import tensorflow 
import tensorflow as tf
print(tf.__version__)

2.8.2


In [ ]:
# creat tensors with tf.constant()
scaler = tf.constant(8)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [ ]:
# check the number of dimensions for a tensor (ndim stands for number of dimesions )
scaler.ndim

0

In [ ]:
# creat a vector 
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# check the dimension of our vector 
vector.ndim

1

In [ ]:
# creat a matrix (has more than 1 dimention)
matrix = tf.constant([[10,7],
                      [7,10]])
matrix
matrix.ndim

2

In [ ]:
# creat another matrix 
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]], dtype = tf.float16) #specify the data type with dtype parameter
another_matrix                              

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
#let's creat a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

** what we've created so far **

* scalar: a single number.
* vector: a number with direction (e.g. wind speed with direction).
* matrix: a 2-dimensional array of numbers.
* tensor: an n-dimensional array of numbers (where n can be any number, a   0-dimension tensor is a scalar, a 1-dimension tensor is a vector).

###### creating tensors with tf.Variable

In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [ ]:
# creat the same tensor with tf.Variable() as above 

changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor , unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# let's try change one of the elements in our changeable tensor 
# let's try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### creating random tensors 

*  Random tensors are tensors of some arbitrary size which contain random numbers.
* Why would you want to create random tensors?

* This is what neural networks use to intialize their weights (patterns) that they're trying to learn in the data.

* For example, the process of a neural network learning often involves taking a random n-dimensional array of numbers and refining them until they represent some kind of pattern (a compressed way to represent the original data).

In [ ]:
# create two random ( but the same ) tensors 

random_1 = tf.random.Generator.from_seed(42)  # set seed for reproduceibility
random_1 = random_1.normal(shape = (2,3))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (2,3))

# are they equal ?
random_1 , random_2 , random_1 == random_2

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True]])>)

#### shuffle the order of elements in a tensor 

In [ ]:
# shuffle a tensor (valuable for when you want to shuffle ur data so the inherent order doesn't effect learning )
not_shuffle = tf.constant([[10,7],
                          [3,4],
                          [2,5]])
not_shuffle.ndim

#shuffle our non-shuffled tensor
tf.random.set_seed(42)        
tf.random.shuffle(not_shuffle , seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### EXERCISE solution 



In [ ]:
# creating the globale seed 

tf.random.set_seed(42)

# making tensors 
random_1 = tf.random.Generator.from_seed(12)
random_1 = random_1.normal(shape=(3, 2))

random_2 = tf.random.Generator.from_seed(14)
random_2 = random_2.normal(shape=(3, 2))

random_3 = tf.random.Generator.from_seed(17)
random_3 = random_3.normal(shape=(3, 2))

random_4 = tf.random.Generator.from_seed(20)
random_4 = random_4.normal(shape=(3, 2))

random_5 = tf.random.Generator.from_seed(12)
random_5 = random_5.normal(shape=(3, 2))

print(random_1 ,random_2 ,random_3 ,random_4 ,random_5)


# shuffling the tensors  # and deciding same system of shuffling or different by controling the seed # Set the operation random seed

a = tf.random.shuffle(random_1)
b = tf.random.shuffle(random_2, seed=42)
c = tf.random.shuffle(random_3, seed=42)
d = tf.random.shuffle(random_4, seed=42)
f = tf.random.shuffle(random_5, seed=42)
print(a)

tf.Tensor(
[[-1.0130816   0.28291714]
 [ 1.2132233   0.46988967]
 [ 0.37944323 -0.6664026 ]], shape=(3, 2), dtype=float32) tf.Tensor(
[[ 0.8045827   0.4769051 ]
 [-0.7812124  -0.996891  ]
 [ 0.33149973 -0.5445254 ]], shape=(3, 2), dtype=float32) tf.Tensor(
[[ 1.5420506  -0.16822556]
 [-0.4390865  -0.4129243 ]
 [ 0.35877243 -1.9095894 ]], shape=(3, 2), dtype=float32) tf.Tensor(
[[ 0.88051325 -1.6833194 ]
 [ 0.86754173 -0.19625713]
 [-1.322665   -0.02279496]], shape=(3, 2), dtype=float32) tf.Tensor(
[[-1.0130816   0.28291714]
 [ 1.2132233   0.46988967]
 [ 0.37944323 -0.6664026 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[ 1.2132233   0.46988967]
 [ 0.37944323 -0.6664026 ]
 [-1.0130816   0.28291714]], shape=(3, 2), dtype=float32)


### other ways to make tensors

In [ ]:
# create a tensor all ones 
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# create a tensor all zeroes
tf.zeros(shape = (3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### turn NumPy arrays into tensors 
the main difference between NumPy arrays and tensorflow tensors is that tensors can be run on a GPU (much faster for numerical computing)

In [ ]:
# you can also turn NumPy arrays into tensors 

# X = tf.constant(some_matrix) # capital for matrix or tensor 
# y = tf.constant(vector) #non-capital for vector 


import numpy as np 

numpy_A = np.arange(1,25,dtype=np.int32) #create a numpy array between 1 to 24
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A , shape = (2,3,4))
B = tf.constant(numpy_A)
A ,B
C = tf.constant(numpy_A , shape = (3,8))
A,B,C

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>)

In [ ]:
A.ndim
B.ndim
C.ndim

2

### Getting informations from tensors 
when dealing with tensors you probably want to be aware of the following attributes 

* shape 
* Rank 
* Axis or dimension 
* Size

In [ ]:
# create a rank 4 tensor (4 dimensions )

rank_4_tensor = tf.zeros(shape = [2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape , rank_4_tensor.ndim , tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of our tensor
print("datatype of every element:", rank_4_tensor.dtype)
print("numbers of dimensions(rank):", rank_4_tensor.ndim)
print("shape of tensor :", rank_4_tensor.shape)
print("elements along 0 axis:", rank_4_tensor.shape[0])
print("elements along last axis :", rank_4_tensor.shape[-1])
print("total number of elements in our tensor :", tf.size(rank_4_tensor))
print("total number of elements in our tensor :", tf.size(rank_4_tensor).numpy())

datatype of every element: <dtype: 'float32'>
numbers of dimensions(rank): 4
shape of tensor : (2, 3, 4, 5)
elements along 0 axis: 2
elements along last axis : 5
total number of elements in our tensor : tf.Tensor(120, shape=(), dtype=int32)
total number of elements in our tensor : 120


### indexing tensors 
tensors can be indexed just like python lists.

In [ ]:
some_list = [ 1,2,3,4,5,6]
some_list[:2]

[1, 2]

In [ ]:
# Get the first 2 elements of each dimension 
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
some_list[:1]

[1]

In [ ]:
# Get the first element from each dimension from each index except the final one 
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [ ]:
# create a rank 2 tensor (2 dimension)
rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor.ndim ,rank_2_tensor.shape ,tf.size(rank_2_tensor)

(2, TensorShape([2, 2]), <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [ ]:
# Get the last item from each row of our rank 2 tensor 
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# add in extra dimension to our rank 2 tensor 
# rank_3_tensor = rank_2_tensor[:,:,tf.newaxis]
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor , axis=-1) # "-1" means expand the final axis 

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# expand 0 axis 
tf.expand_dims(rank_2_tensor , axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor , axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

### Manipulating tensors ( tensors operations )
** Basic operations **


'+' , '- ' , ' * ' , ' / ' 

In [ ]:
# you can add values to a tensor using the addition operator 
tensor = tf.constant ([[10,7],
                       [3,4]])


In [ ]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Orignal tensor is unchanged 
tensor = tensor +10
tensor 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# multiplication also works 
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]], dtype=int32)>

In [ ]:
# substraction if you want 
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# we can use the tensorflow built-in function too
tf.multiply( tensor,10 )                     # faster when u use GPU

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]], dtype=int32)>

### Matrix multiplication

its one of the most used 

In [ ]:
# matrix multiplication in tensorflow 

print(tensor)
tf.matmul(tensor ,tensor)     # dot multiplication

tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]], dtype=int32)>

In [ ]:
tensor , tensor 

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]], dtype=int32)>)

In [ ]:
tensor * tensor     # element wise 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[400, 289],
       [169, 196]], dtype=int32)>

In [ ]:
# matrix multiplication with python operator "@"
tensor @ tensor           # dot multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]], dtype=int32)>

In [ ]:
# create a tensor (3,2) tensor 
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
# create another (3,2) tensor
Y = tf.constant([[7,8],
                [9,10],
                [11,12]])
X ,Y


(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# lets change the shape of Y 
tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
# try to matrix multiply x by reshaped y 
X @ tf.reshape(Y , shape=(2,3))


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# can we do the same with transpose         # difference between transpose and reshape 

X , tf.transpose(X) , tf.reshape(X, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [ ]:
# try matrix multipliction with transpose rather than reshape
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

*** the dot product ***

Multiplying matrices by each other is also referred to as the dot product.

You can perform the operation using 
* tf.matmul()
* tf.tensordot()

In [ ]:
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# preform the dot product on X and Y (requires X or Y to be transposed )
tf.tensordot(tf.transpose(X),Y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# prefurm matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
# prefurm matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape = (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# check the values of Y (reshaped), and Y (transposed)
print("Normal Y:")
print(Y, "\n") # "\n" for newline

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


## changing the data type of a tensor 

In [ ]:
# create a new tensor with default datatype (float32)
B = tf.constant([1.7,1.3])
B.dtype

tf.float32

In [ ]:
C = tf.constant([10,7])
C.dtype

tf.int32

In [ ]:
# change from float32 to float16 (reduced precision)
D = tf.cast(B,dtype = tf.float16)
D , D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 1.3], dtype=float16)>,
 tf.float16)

In [ ]:
# change from int32 to float32 
E = tf.cast(C , dtype = tf.float32 )
E , E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10.,  7.], dtype=float32)>,
 tf.float32)

### aggregating tensors

aggregating tensors = condensing them from multiple values down to a smaller amount of values 

In [ ]:
# Get the absolute values
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

## let's go through the following forms of aggregation
* Get the minimum
* Get the maximum
* Get the mean of a tensor 
* Get the sum of a tensor 


In [ ]:
# create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([21, 88, 75, 88, 51, 58, 99, 59, 20,  5, 53, 68, 23, 26, 32, 20, 92,
       30, 90, 16, 35,  1, 22, 95, 78, 95, 34, 64, 27,  7, 56, 28, 16, 86,
       80, 86, 82, 34, 82, 76, 59,  6, 84, 56, 92, 27, 16, 56, 90, 77])>

In [ ]:
tf.size(E) , E.shape , E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
# find the max 
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
# find the mean 
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=53>

In [ ]:
# find the sum 
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2661>

In [ ]:
# To find the variance of our tensor , we need access to tensorflow_probability

import tensorflow_probability as tfp

tfp.stats.variance(E)


<tf.Tensor: shape=(), dtype=int64, numpy=906>

In [ ]:
# get the variance of the tensor
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=906.6916>

In [ ]:
# find the std of our tensor

tf.math.reduce_std(tf.cast(E , dtype =tf.float32))


<tf.Tensor: shape=(), dtype=float32, numpy=30.11132>

### Find the positional maximum and minimum

In [ ]:
# create a new tensor for finding positional min and max   # it get the index position for max or min value
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# find the positional max 

tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# index on our largest value position 
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# find the max value of f
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# find the positional min 
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# find the min using the positional min index 
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (removing all singl dimensions)

In [ ]:
# creat a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape= [50]),shape=(1,1,1,1,50) )
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed =tf.squeeze(G)
G_squeezed , G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### one-Hot-encoding tensors 

In [ ]:
# create a list of indices

some_list = [0,1,2,3] # could be red , green ,blue, purple

# one-hot-encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# specify custom values for one hot encoding 
tf.one_hot(some_list , depth = 4 , on_value='yo i love deep learning ', off_value='i also like to code')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo i love deep learning ', b'i also like to code',
        b'i also like to code', b'i also like to code'],
       [b'i also like to code', b'yo i love deep learning ',
        b'i also like to code', b'i also like to code'],
       [b'i also like to code', b'i also like to code',
        b'yo i love deep learning ', b'i also like to code'],
       [b'i also like to code', b'i also like to code',
        b'i also like to code', b'yo i love deep learning ']],
      dtype=object)>

### squaring , log , square root

In [ ]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# square it 
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# find the square root (will error , method requries non-int type)
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
# find the log (will error , method requries non-int type)
tf.math.log(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy

tensorflow interacts beautifully with numpy

In [ ]:
# create a tensor directly from numpy arry 
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# convert our tensor back to a numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# convert tensor J to a numpy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [ ]:
# the default types of each are slightly different 
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])
# check the datatype of each 
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)